version: "3"
# from https://github.com/nissbran/eventstore-cluster-docker-compose/tree/master/local-3-node-dns-cluster
services:

  php:
    image: prooph/php:7.2-cli
    volumes:
      - ./..:/app
    command: tail -f /dev/null
    networks:
      clusternetwork:

  eventstore1:
   image: eventstore/eventstore:release-4.1.0
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_CLUSTER_DNS=escluster.net
     - EVENTSTORE_EXT_HTTP_PORT=2113
     - EVENTSTORE_EXT_TCP_PORT=1113
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2113/
   ports:
     - 1113:1113
     - 2113:2113
   volumes:
     - "~/Data/eventstoredns3node/node1:/var/lib/eventstore"
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
   networks:
     clusternetwork:
       aliases:
        - escluster.net

  eventstore2:
   image: eventstore/eventstore:release-4.1.0
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_CLUSTER_DNS=escluster.net
     - EVENTSTORE_EXT_HTTP_PORT=2123
     - EVENTSTORE_EXT_TCP_PORT=1123
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2123/
   ports:
     - 1123:1123
     - 2123:2123
   volumes:
     - "~/Data/eventstoredns3node/node2:/var/lib/eventstore"
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2123/stats || exit 1"]
      interval: 5s
      timeout: 2s
   networks:
     clusternetwork:
       aliases:
        - escluster.net

  eventstore3:
   image: eventstore/eventstore:release-4.1.0
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_CLUSTER_DNS=escluster.net
     - EVENTSTORE_EXT_HTTP_PORT=2133
     - EVENTSTORE_EXT_TCP_PORT=1133
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2133/
   ports:
     - 1133:1133
     - 2133:2133
   volumes:
     - "~/Data/eventstoredns3node/node3:/var/lib/eventstore"
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2133/stats || exit 1"]
      interval: 5s
      timeout: 2s
   networks:
     clusternetwork:
       aliases:
        - escluster.net

networks:
  clusternetwork:
    driver: bridge
